@startuml uml
class Redis {
    private Validation validation
    private Connect connect
    private Create create
    private Read read
    private Update update
    private Erase erase
    public Redis(const char* addr, int port)
    public int create()
    public int read()
    public int update()
    public int erase()
}
class Connect {
    private int redis_socket
    private int connect_status
    public Connect(const char* addr, int port)
    public int send(int type, const char* query)
}
class Validation
class Create
class Read
class Update
class Delete
@enduml